version: "3.7"
services:
  app:
    build:
      args:
        user: nguyenthang327
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: hotel-booking-image
    container_name: hotel-booking-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - hotel-booking
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    container_name: hotel-booking-db
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}

      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - hotel-booking
  nginx:
    image: nginx:alpine
    container_name: hotel-booking-nginx
    restart: unless-stopped
    ports:
      - 8091:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - hotel-booking
networks:
  hotel-booking:
    driver: bridge
